version: '2'

services:
  db:
    privileged: true
    image: postgres:10.0
    networks:
      - icw-backend
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=icw
      - POSTGRES_PASSWORD=icw
  web:
    privileged: true
    build: ./server/
    ports:
      - 80:80
    volumes:
      - ./server:/server
      - ./client/dist:/template
      - ./storage:/storage
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=icw
      - POSTGRES_PASSWORD=icw
    command:
      flask run --host=0.0.0.0 --port=80
    networks:
      - icw-backend
    depends_on:
      - db

networks:
  icw-backend:
    driver: bridge

volumes:
  db-data:
